# Generated by Django 5.0.3 on 2024-04-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('country_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(default='project title', max_length=50)),
                ('project_details', models.TextField()),
                ('announced_date', models.DateTimeField(auto_now_add=True, verbose_name='Announced Date')),
                ('completion_date', models.DateTimeField(verbose_name='Completion Date')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('no_of_task_assigned', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(to='tasks.contributor')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=70)),
                ('announced_date', models.DateTimeField(auto_now_add=True, verbose_name='Announced Date')),
                ('completion_date', models.DateTimeField(verbose_name='Completion Date')),
                ('associated_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.project')),
                ('assigned_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.team')),
            ],
        ),
    ]
