# Generated by Django 5.0.3 on 2024-04-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='associated_project',
        ),
    ]
